2025-05-04 19:26:54,442 - app - INFO - POSTGRES connection success.
2025-05-04 19:27:25,559 - app - INFO - Fetching profile for user 1058681922
2025-05-04 19:27:25,565 - app - WARNING - Profile not found for user 1058681922
2025-05-04 19:27:27,536 - app - INFO - Fetching profile for user 1058681922
2025-05-04 19:27:27,537 - app - WARNING - Profile not found for user 1058681922
2025-05-04 19:27:38,247 - app - INFO - Starting video verification for user 1058681922
2025-05-04 19:27:38,379 - app - INFO - Video verification completed for user 1058681922
2025-05-04 19:28:25,881 - app - INFO - Starting profile save for user 1058681922
2025-05-04 19:28:26,064 - app - INFO - Profile saved successfully for user 1058681922
2025-05-04 19:28:26,294 - app - INFO - Starting file upload: 1058681922_AgACAgIAAxkBAAIdYGgXwDoDhyxs5VLPZ9ariIdce3YMAAIO8zEbJwzBSFWJaLhZysTSAQADAgADeAADNgQ.jpg
2025-05-04 19:28:26,460 - app - INFO - File uploaded successfully: 1058681922_AgACAgIAAxkBAAIdYGgXwDoDhyxs5VLPZ9ariIdce3YMAAIO8zEbJwzBSFWJaLhZysTSAQADAgADeAADNgQ.jpg
2025-05-04 19:28:26,618 - app - INFO - Starting file upload: 1058681922_AgACAgIAAxkBAAIdYWgXwDr0e8fK3gABMZjGPEp9qCAJ6AACD_MxGycMwUjNadxRSF2fDQEAAwIAA3gAAzYE.jpg
2025-05-04 19:28:26,666 - app - INFO - File uploaded successfully: 1058681922_AgACAgIAAxkBAAIdYWgXwDr0e8fK3gABMZjGPEp9qCAJ6AACD_MxGycMwUjNadxRSF2fDQEAAwIAA3gAAzYE.jpg
2025-05-04 19:28:26,673 - app - INFO - Saving media for user 1058681922
2025-05-04 19:28:26,681 - app - INFO - Media saved successfully for user 1058681922
2025-05-04 19:28:33,550 - app - INFO - Fetching profile for user 1058681922
2025-05-04 19:28:33,552 - app - INFO - Profile retrieved successfully for user 1058681922
2025-05-04 19:28:33,554 - app - INFO - Fetching profile for user 1058681922
2025-05-04 19:28:33,555 - app - INFO - Profile retrieved successfully for user 1058681922
2025-05-04 19:28:33,601 - app - INFO - Fetching media for user 1058681922
2025-05-04 19:28:33,603 - app - INFO - Media retrieved successfully for user 1058681922
2025-05-04 19:28:33,652 - app - INFO - Generating presigned URL for key: 7382e738beda4b4684c4978a08cf0723.jpg
2025-05-04 19:28:33,653 - app - INFO - Presigned URL generated for key: 7382e738beda4b4684c4978a08cf0723.jpg
2025-05-04 19:28:33,656 - app - INFO - Generating presigned URL for key: 0b75741508c447f38225979b5373f628.jpg
2025-05-04 19:28:33,657 - app - INFO - Presigned URL generated for key: 0b75741508c447f38225979b5373f628.jpg
2025-05-04 21:20:24,102 - app - INFO - POSTGRES connection success.
2025-05-04 21:21:50,549 - app - INFO - POSTGRES connection success.
2025-05-04 21:28:40,056 - app - INFO - POSTGRES connection success.
2025-05-04 21:29:15,896 - app - INFO - POSTGRES connection success.
2025-05-04 21:38:20,506 - app - INFO - POSTGRES connection success.
2025-05-04 21:38:47,750 - app - INFO - Fetching profile for user 1058681922
2025-05-04 21:38:47,757 - app - WARNING - Profile not found for user 1058681922
2025-05-04 21:42:40,650 - app - INFO - POSTGRES connection success.
2025-05-04 21:43:19,834 - app - INFO - POSTGRES connection success.
2025-05-04 21:43:46,764 - app - INFO - POSTGRES connection success.
2025-05-04 21:43:53,177 - app - INFO - POSTGRES connection success.
2025-05-04 21:43:59,589 - app - INFO - POSTGRES connection success.
2025-05-04 21:44:13,307 - app - INFO - POSTGRES connection success.
2025-05-04 21:45:04,793 - app - INFO - POSTGRES connection success.
2025-05-04 21:54:18,329 - app - INFO - POSTGRES connection success.
2025-05-04 21:58:42,780 - app - INFO - Fetching profile for user 1058681922
2025-05-04 21:58:42,787 - app - WARNING - Profile not found for user 1058681922
2025-05-04 21:58:44,011 - app - INFO - Fetching profile for user 1058681922
2025-05-04 21:58:44,013 - app - WARNING - Profile not found for user 1058681922
2025-05-04 21:58:58,007 - app - INFO - Starting video verification for user 1058681922
2025-05-04 21:58:58,026 - app - INFO - Video verification completed for user 1058681922
2025-05-04 21:59:52,673 - app - INFO - Starting profile save for user 1058681922
2025-05-04 21:59:53,031 - app - INFO - Profile saved successfully for user 1058681922
2025-05-04 21:59:53,268 - app - INFO - Starting file upload: 1058681922_AgACAgIAAxkBAAIDs2gX470I28s9U8X49i51t5QEIPWoAAIP8zEbJwzBSCU6ceAL56akAQADAgADeAADNgQ.jpg
2025-05-04 21:59:53,385 - app - INFO - File uploaded successfully: 1058681922_AgACAgIAAxkBAAIDs2gX470I28s9U8X49i51t5QEIPWoAAIP8zEbJwzBSCU6ceAL56akAQADAgADeAADNgQ.jpg
2025-05-04 21:59:53,389 - app - INFO - Saving media for user 1058681922
2025-05-04 21:59:53,396 - app - INFO - Media saved successfully for user 1058681922
2025-05-04 22:00:05,289 - app - INFO - Fetching profile for user 7717579491
2025-05-04 22:00:05,291 - app - WARNING - Profile not found for user 7717579491
2025-05-04 22:00:06,491 - app - INFO - Fetching profile for user 7717579491
2025-05-04 22:00:06,492 - app - WARNING - Profile not found for user 7717579491
2025-05-04 22:00:18,206 - app - INFO - Starting video verification for user 7717579491
2025-05-04 22:00:18,211 - app - INFO - Video verification completed for user 7717579491
2025-05-04 22:01:16,060 - app - INFO - Starting profile save for user 7717579491
2025-05-04 22:01:16,111 - app - INFO - Profile saved successfully for user 7717579491
2025-05-04 22:01:16,431 - app - INFO - Starting file upload: 7717579491_AgACAgIAAxkBAAIDzmgX5BBl-MzTv08bRLOLAAHGqdWeywAC4fcxG8frwUjVnvl2sLoRvQEAAwIAA3kAAzYE.jpg
2025-05-04 22:01:16,569 - app - INFO - File uploaded successfully: 7717579491_AgACAgIAAxkBAAIDzmgX5BBl-MzTv08bRLOLAAHGqdWeywAC4fcxG8frwUjVnvl2sLoRvQEAAwIAA3kAAzYE.jpg
2025-05-04 22:01:16,573 - app - INFO - Saving media for user 7717579491
2025-05-04 22:01:16,577 - app - INFO - Media saved successfully for user 7717579491
2025-05-04 22:01:18,468 - app - INFO - Fetching profile for user 7717579491
2025-05-04 22:01:18,470 - app - INFO - Profile retrieved successfully for user 7717579491
2025-05-04 22:01:18,474 - app - INFO - Fetching profile for user 7717579491
2025-05-04 22:01:18,475 - app - INFO - Profile retrieved successfully for user 7717579491
2025-05-04 22:01:18,519 - app - INFO - Fetching media for user 7717579491
2025-05-04 22:01:18,521 - app - INFO - Media retrieved successfully for user 7717579491
2025-05-04 22:01:18,569 - app - INFO - Generating presigned URL for key: 8b548d995abc43f293a259404f9ffa69.jpg
2025-05-04 22:01:18,570 - app - INFO - Presigned URL generated for key: 8b548d995abc43f293a259404f9ffa69.jpg
2025-05-04 22:01:20,777 - app - INFO - Fetching profile for user 7717579491
2025-05-04 22:01:20,778 - app - INFO - Profile retrieved successfully for user 7717579491
2025-05-04 22:01:20,783 - app - INFO - Starting to get recommendations for user 7717579491, count: 30
2025-05-04 22:01:20,830 - app - ERROR - Failed to get recommendations for user 7717579491: Invalid input of type: 'tuple'. Convert to a bytes, string, int or float first.
Traceback (most recent call last):
  File "/app/api/recsys.py", line 22, in get_recommendations
    result = await recommendations_service.get_recommendations(user_id, count)
  File "/app/services/recsys/RecommendationsService.py", line 10, in get_recommendations
    recommendations = await self.recommender.get_hybrid_recommendations(user_id, count)
  File "/app/recsys/EmbeddingRecommender.py", line 182, in get_hybrid_recommendations
    await self.recommendation_cache.set(user_id, final_results)
  File "/app/cache/RecommendationCache.py", line 26, in set
    await pipe.execute()
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/client.py", line 1598, in execute
    return await conn.retry.call_with_retry(
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/retry.py", line 71, in call_with_retry
    return await do()
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/client.py", line 1427, in _execute_transaction
    all_cmds = connection.pack_commands(
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/connection.py", line 683, in pack_commands
    for chunk in self.pack_command(*cmd):
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/connection.py", line 646, in pack_command
    for arg in map(self.encoder.encode, args):
  File "/usr/local/lib/python3.10/site-packages/redis/_parsers/encoders.py", line 29, in encode
    raise DataError(
redis.exceptions.DataError: Invalid input of type: 'tuple'. Convert to a bytes, string, int or float first.
2025-05-04 22:01:26,418 - app - INFO - Fetching profile for user 7717579491
2025-05-04 22:01:26,419 - app - INFO - Profile retrieved successfully for user 7717579491
2025-05-04 22:01:26,423 - app - INFO - Starting to get recommendations for user 7717579491, count: 30
2025-05-04 22:01:26,426 - app - ERROR - Failed to get recommendations for user 7717579491: Invalid input of type: 'tuple'. Convert to a bytes, string, int or float first.
Traceback (most recent call last):
  File "/app/api/recsys.py", line 22, in get_recommendations
    result = await recommendations_service.get_recommendations(user_id, count)
  File "/app/services/recsys/RecommendationsService.py", line 10, in get_recommendations
    recommendations = await self.recommender.get_hybrid_recommendations(user_id, count)
  File "/app/recsys/EmbeddingRecommender.py", line 182, in get_hybrid_recommendations
    await self.recommendation_cache.set(user_id, final_results)
  File "/app/cache/RecommendationCache.py", line 26, in set
    await pipe.execute()
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/client.py", line 1598, in execute
    return await conn.retry.call_with_retry(
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/retry.py", line 71, in call_with_retry
    return await do()
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/client.py", line 1427, in _execute_transaction
    all_cmds = connection.pack_commands(
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/connection.py", line 683, in pack_commands
    for chunk in self.pack_command(*cmd):
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/connection.py", line 646, in pack_command
    for arg in map(self.encoder.encode, args):
  File "/usr/local/lib/python3.10/site-packages/redis/_parsers/encoders.py", line 29, in encode
    raise DataError(
redis.exceptions.DataError: Invalid input of type: 'tuple'. Convert to a bytes, string, int or float first.
2025-05-04 22:01:26,620 - app - INFO - Fetching profile for user 7717579491
2025-05-04 22:01:26,628 - app - INFO - Profile retrieved successfully for user 7717579491
2025-05-04 22:01:26,656 - app - INFO - Starting to get recommendations for user 7717579491, count: 30
2025-05-04 22:01:26,660 - app - ERROR - Failed to get recommendations for user 7717579491: Invalid input of type: 'tuple'. Convert to a bytes, string, int or float first.
Traceback (most recent call last):
  File "/app/api/recsys.py", line 22, in get_recommendations
    result = await recommendations_service.get_recommendations(user_id, count)
  File "/app/services/recsys/RecommendationsService.py", line 10, in get_recommendations
    recommendations = await self.recommender.get_hybrid_recommendations(user_id, count)
  File "/app/recsys/EmbeddingRecommender.py", line 182, in get_hybrid_recommendations
    await self.recommendation_cache.set(user_id, final_results)
  File "/app/cache/RecommendationCache.py", line 26, in set
    await pipe.execute()
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/client.py", line 1598, in execute
    return await conn.retry.call_with_retry(
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/retry.py", line 71, in call_with_retry
    return await do()
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/client.py", line 1427, in _execute_transaction
    all_cmds = connection.pack_commands(
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/connection.py", line 683, in pack_commands
    for chunk in self.pack_command(*cmd):
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/connection.py", line 646, in pack_command
    for arg in map(self.encoder.encode, args):
  File "/usr/local/lib/python3.10/site-packages/redis/_parsers/encoders.py", line 29, in encode
    raise DataError(
redis.exceptions.DataError: Invalid input of type: 'tuple'. Convert to a bytes, string, int or float first.
2025-05-04 22:01:39,618 - app - INFO - Fetching profile for user 7717579491
2025-05-04 22:01:39,621 - app - INFO - Profile retrieved successfully for user 7717579491
2025-05-04 22:01:39,625 - app - INFO - Starting to get recommendations for user 7717579491, count: 30
2025-05-04 22:01:39,630 - app - ERROR - Failed to get recommendations for user 7717579491: Invalid input of type: 'tuple'. Convert to a bytes, string, int or float first.
Traceback (most recent call last):
  File "/app/api/recsys.py", line 22, in get_recommendations
    result = await recommendations_service.get_recommendations(user_id, count)
  File "/app/services/recsys/RecommendationsService.py", line 10, in get_recommendations
    recommendations = await self.recommender.get_hybrid_recommendations(user_id, count)
  File "/app/recsys/EmbeddingRecommender.py", line 182, in get_hybrid_recommendations
    await self.recommendation_cache.set(user_id, final_results)
  File "/app/cache/RecommendationCache.py", line 26, in set
    await pipe.execute()
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/client.py", line 1598, in execute
    return await conn.retry.call_with_retry(
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/retry.py", line 71, in call_with_retry
    return await do()
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/client.py", line 1427, in _execute_transaction
    all_cmds = connection.pack_commands(
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/connection.py", line 683, in pack_commands
    for chunk in self.pack_command(*cmd):
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/connection.py", line 646, in pack_command
    for arg in map(self.encoder.encode, args):
  File "/usr/local/lib/python3.10/site-packages/redis/_parsers/encoders.py", line 29, in encode
    raise DataError(
redis.exceptions.DataError: Invalid input of type: 'tuple'. Convert to a bytes, string, int or float first.
2025-05-04 22:07:27,623 - app - INFO - POSTGRES connection success.
